Traceback (most recent call last):
  File "/home/runner/micromamba/envs/data_science/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/micromamba/envs/data_science/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/micromamba/envs/data_science/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/home/runner/micromamba/envs/data_science/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/runner/micromamba/envs/data_science/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/runner/micromamba/envs/data_science/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/micromamba/envs/data_science/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
smallest_chatbot_in_the_world()
------------------

----- stdout -----
Hi. What's up?
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
Cell [0;32mIn[28], line 1[0m
[0;32m----> 1[0m [43msmallest_chatbot_in_the_world[49m[43m([49m[43m)[49m

Cell [0;32mIn[27], line 5[0m, in [0;36msmallest_chatbot_in_the_world[0;34m()[0m
[1;32m      3[0m [38;5;28;01mdef[39;00m [38;5;21msmallest_chatbot_in_the_world[39m():
[1;32m      4[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mHi. What[39m[38;5;124m'[39m[38;5;124ms up?[39m[38;5;124m"[39m)
[0;32m----> 5[0m     user_input [38;5;241m=[39m [38;5;28;43minput[39;49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43m>>> [39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      7[0m     [38;5;66;03m# mini chat-bot[39;00m
[1;32m      8[0m     regex_problem [38;5;241m=[39m [38;5;124mr[39m[38;5;124m"[39m[38;5;124m(problem|issue[s]?) with ([a-zA-Z[39m[38;5;124m\[39m[38;5;124ms]*[39m[38;5;124m\[39m[38;5;124mb)[39m[38;5;124m"[39m

File [0;32m~/micromamba/envs/data_science/lib/python3.9/site-packages/ipykernel/kernelbase.py:1260[0m, in [0;36mKernel.raw_input[0;34m(self, prompt)[0m
[1;32m   1258[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_allow_stdin:
[1;32m   1259[0m     msg [38;5;241m=[39m [38;5;124m"[39m[38;5;124mraw_input was called, but this frontend does not support input requests.[39m[38;5;124m"[39m
[0;32m-> 1260[0m     [38;5;28;01mraise[39;00m StdinNotImplementedError(msg)
[1;32m   1261[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_input_request(
[1;32m   1262[0m     [38;5;28mstr[39m(prompt),
[1;32m   1263[0m     [38;5;28mself[39m[38;5;241m.[39m_parent_ident[[38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m],
[1;32m   1264[0m     [38;5;28mself[39m[38;5;241m.[39mget_parent([38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m),
[1;32m   1265[0m     password[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m   1266[0m )

[0;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.

